"""Assemble specialist reports + synthesis into final research document."""

from __future__ import annotations

import logging
import re
from datetime import date
from pathlib import Path

import markdown

logger = logging.getLogger(__name__)


_VAULT_BASE = Path.home() / "vault" / "stocks"
_REPORTS_DIR = Path(__file__).parent.parent.parent / "reports"


def assemble_final_report(
    symbol: str,
    specialist_envelopes: dict,  # {name: BriefingEnvelope}
    synthesis_envelope,  # BriefingEnvelope
) -> tuple[Path, Path]:
    """Assemble all reports into final Markdown + HTML.

    Returns (markdown_path, html_path).
    """
    import time as _time
    asm_start = _time.time()
    symbol = symbol.upper()
    today = date.today().isoformat()
    logger.info("[assembly] %s: started (%d specialist reports)", symbol, len(specialist_envelopes))

    # Extract synthesis sections by splitting on ## headers
    synthesis_sections = _split_by_headers(synthesis_envelope.report)

    # Build final markdown
    parts = []

    # Title + metadata
    # Try to get company name from business briefing
    biz = specialist_envelopes.get("business")
    company_name = ""
    if biz and biz.briefing:
        company_name = biz.briefing.get("company_name", symbol)

    parts.append(f"# {company_name or symbol} ({symbol}) — Equity Research Report")
    parts.append(
        f"\n*Generated: {today} | Multi-agent research system"
        f" (8 specialists + macro + synthesis + verification)*\n"
    )
    parts.append("---\n")

    # Synthesis sections first (Verdict, Executive Summary, Key Signals)
    for header in ["Verdict", "Executive Summary", "Key Signals"]:
        section = _find_section(synthesis_sections, header)
        if section:
            parts.append(section)
            parts.append("\n---\n")

    # Specialist reports in order
    report_order = [
        ("business", "The Business"),
        ("financials", "Financial Analysis"),
        ("valuation", "Valuation"),
        ("ownership", "Ownership Intelligence"),
        ("risk", "Risk Assessment"),
        ("macro", "Macro Backdrop & Secular Tailwinds"),
        ("sector", "Sector & Industry"),
        ("technical", "Technical & Market Context"),
        ("news", "Recent News & Catalysts"),
    ]

    for agent_name, section_title in report_order:
        env = specialist_envelopes.get(agent_name)
        if env and env.report:
            # Strip preamble text (agent's thinking/tool-calling messages before the report)
            cleaned = _strip_preamble(env.report)
            parts.append(cleaned)
            parts.append("\n---\n")

    # Web research section (resolved open questions)
    web_env = specialist_envelopes.get("web_research")
    if web_env and web_env.report and len(web_env.report.strip()) > 100:
        cleaned = _strip_preamble(web_env.report)
        # Strip the trailing JSON briefing block from the report
        json_start = cleaned.rfind("```json")
        if json_start > 0:
            cleaned = cleaned[:json_start].rstrip()
        parts.append(cleaned)
        parts.append("\n---\n")

    # Synthesis closing sections (Catalysts, Big Question)
    for header in ["Catalysts", "What to Watch", "Big Question"]:
        section = _find_section(synthesis_sections, header)
        if section:
            parts.append(section)
            parts.append("\n---\n")

    # Cost summary
    total_cost = sum(e.cost.total_cost_usd for e in specialist_envelopes.values())
    total_cost += synthesis_envelope.cost.total_cost_usd
    parts.append(
        f"\n*Report generated by multi-agent research system."
        f" Total cost: ${total_cost:.2f}*\n"
    )

    final_md = "\n".join(parts)

    # Save markdown
    vault_dir = _VAULT_BASE / symbol / "thesis"
    vault_dir.mkdir(parents=True, exist_ok=True)
    md_path = vault_dir / f"{today}.md"
    md_path.write_text(final_md, encoding="utf-8")

    # Also save to reports dir
    _REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    reports_md = _REPORTS_DIR / f"{symbol.lower()}-thesis.md"
    reports_md.write_text(final_md, encoding="utf-8")

    # Generate HTML
    html_content = _render_html(final_md, symbol, company_name, today)
    html_path = _REPORTS_DIR / f"{symbol.lower()}-thesis.html"
    html_path.write_text(html_content, encoding="utf-8")

    logger.info("[assembly] %s: done %.1fs, %d chars md, %d chars html",
                symbol, _time.time() - asm_start, len(final_md), len(html_content))
    return md_path, html_path


def _strip_preamble(report: str) -> str:
    """Strip agent thinking/tool-calling preamble before the actual report content.

    The agent often starts with messages like "I'll start by..." or "Let me pull..."
    before the actual report which starts with a # or ## header or ---.
    """
    lines = report.split("\n")
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("#") or stripped.startswith("---"):
            return "\n".join(lines[i:])
    return report  # no header found, return as-is


def _split_by_headers(text: str) -> dict[str, str]:
    """Split markdown text by ## headers into {header_text: section_content}."""
    sections: dict[str, str] = {}
    current_header = ""
    current_lines: list[str] = []

    for line in text.split("\n"):
        if line.startswith("## "):
            if current_header:
                sections[current_header] = "\n".join(current_lines)
            current_header = line[3:].strip()
            current_lines = [line]
        else:
            current_lines.append(line)

    if current_header:
        sections[current_header] = "\n".join(current_lines)

    return sections


def _find_section(sections: dict[str, str], keyword: str) -> str | None:
    """Find a section whose header contains the keyword (case-insensitive)."""
    keyword_lower = keyword.lower()
    for header, content in sections.items():
        if keyword_lower in header.lower():
            return content
    return None


def _render_html(
    md_content: str, symbol: str, company_name: str, report_date: str
) -> str:
    """Convert markdown to styled HTML with mermaid.js support."""
    # Extract mermaid blocks before markdown conversion
    mermaid_blocks: dict[str, str] = {}
    counter = 0

    def replace_mermaid(match: re.Match) -> str:
        nonlocal counter
        counter += 1
        placeholder = f"MERMAID_PLACEHOLDER_{counter}"
        mermaid_blocks[placeholder] = match.group(1).strip()
        return placeholder

    md_processed = re.sub(
        r"```mermaid\s*\n(.*?)```",
        replace_mermaid,
        md_content,
        flags=re.DOTALL,
    )

    # Convert markdown to HTML
    html_body = markdown.markdown(
        md_processed,
        extensions=["tables", "fenced_code", "codehilite", "toc"],
    )

    # Replace mermaid placeholders with <pre class="mermaid"> blocks
    for placeholder, mermaid_code in mermaid_blocks.items():
        html_body = html_body.replace(
            f"<p>{placeholder}</p>",
            f'<pre class="mermaid">{mermaid_code}</pre>',
        )
        # Also handle case where it's not wrapped in <p>
        html_body = html_body.replace(
            placeholder,
            f'<pre class="mermaid">{mermaid_code}</pre>',
        )

    title = f"{company_name or symbol} ({symbol}) — Research Report"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        :root {{
            --bg-dark: #1B1B1B;
            --bg-light: #F5F0EB;
            --surface: #EDE8E3;
            --accent-1: #C4533A;
            --accent-2: #2B5EA7;
            --text-dark: #1A1612;
            --text-light: #F5F0EB;
            --green: #4ecca3;
            --red: #e94560;
            --yellow: #f0a500;
        }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: 'Lato', -apple-system, BlinkMacSystemFont, sans-serif;
            background: var(--bg-dark);
            color: var(--text-light);
            line-height: 1.7;
            font-size: 16px;
            max-width: 900px;
            margin: 0 auto;
            padding: 2rem;
        }}
        h1 {{
            font-family: 'Raleway', sans-serif;
            font-size: 2.2rem;
            font-weight: 300;
            color: var(--accent-1);
            margin: 1.5rem 0;
            border-bottom: 2px solid var(--accent-1);
            padding-bottom: 0.5rem;
        }}
        h2 {{
            font-family: 'Raleway', sans-serif;
            font-size: 1.6rem;
            font-weight: 700;
            color: var(--accent-2);
            margin: 2rem 0 1rem;
        }}
        h3 {{
            font-size: 1.2rem;
            font-weight: 700;
            color: var(--text-light);
            margin: 1.5rem 0 0.5rem;
        }}
        p {{ margin: 0.8rem 0; }}
        a {{ color: var(--accent-2); text-decoration: underline; }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 1rem 0;
            font-size: 0.9rem;
        }}
        th {{
            background: var(--accent-2);
            color: white;
            padding: 0.6rem;
            text-align: left;
            font-weight: 700;
        }}
        td {{
            padding: 0.5rem 0.6rem;
            border-bottom: 1px solid #333;
        }}
        tr:nth-child(even) {{ background: rgba(255,255,255,0.03); }}
        tr:hover {{ background: rgba(255,255,255,0.07); }}
        strong {{ color: var(--accent-1); }}
        em {{ color: #aaa; font-style: italic; }}
        blockquote {{
            border-left: 3px solid var(--accent-1);
            padding: 0.5rem 1rem;
            margin: 1rem 0;
            background: rgba(255,255,255,0.03);
            font-style: italic;
        }}
        code {{
            background: rgba(255,255,255,0.08);
            padding: 0.15rem 0.4rem;
            border-radius: 3px;
            font-size: 0.85em;
        }}
        pre {{
            background: rgba(255,255,255,0.05);
            padding: 1rem;
            border-radius: 5px;
            overflow-x: auto;
            margin: 1rem 0;
        }}
        pre.mermaid {{
            background: transparent;
            text-align: center;
        }}
        hr {{
            border: none;
            border-top: 1px solid #333;
            margin: 2rem 0;
        }}
        ul, ol {{ padding-left: 1.5rem; margin: 0.5rem 0; }}
        li {{ margin: 0.3rem 0; }}
        .metadata {{
            color: #888;
            font-size: 0.9rem;
            margin-bottom: 2rem;
        }}
    </style>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;700&family=Lato:wght@300;400;700&display=swap" rel="stylesheet">
</head>
<body>
    {html_body}
    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
        mermaid.initialize({{ startOnLoad: true, theme: 'dark' }});
    </script>
</body>
</html>"""


def assemble_comparison_report(
    symbols: list[str],
    comparison_envelope,
) -> tuple[Path, Path]:
    """Assemble a comparison report from the comparison agent's output.

    Returns (html_path, md_path).
    """
    report_md = comparison_envelope.report
    today = date.today().isoformat()

    sym_slug = "-vs-".join(s.lower() for s in symbols)

    # Save markdown to vault
    vault_dir = _VAULT_BASE / "_comparisons" / sym_slug
    vault_dir.mkdir(parents=True, exist_ok=True)
    md_path = vault_dir / f"{today}.md"
    md_path.write_text(report_md, encoding="utf-8")

    # Save HTML to reports dir
    _REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    html_path = _REPORTS_DIR / f"{sym_slug}-comparison.html"
    html_content = _render_comparison_html(symbols, report_md)
    html_path.write_text(html_content, encoding="utf-8")

    return html_path, md_path


def _render_comparison_html(symbols: list[str], md_content: str) -> str:
    """Render comparison report as styled HTML, reusing thesis report styling."""
    # Extract mermaid blocks before markdown conversion
    mermaid_blocks: dict[str, str] = {}
    counter = 0

    def replace_mermaid(match: re.Match) -> str:
        nonlocal counter
        counter += 1
        placeholder = f"MERMAID_PLACEHOLDER_{counter}"
        mermaid_blocks[placeholder] = match.group(1).strip()
        return placeholder

    md_processed = re.sub(
        r"```mermaid\s*\n(.*?)```",
        replace_mermaid,
        md_content,
        flags=re.DOTALL,
    )

    html_body = markdown.markdown(
        md_processed,
        extensions=["tables", "fenced_code", "codehilite", "toc"],
    )

    for placeholder, mermaid_code in mermaid_blocks.items():
        html_body = html_body.replace(
            f"<p>{placeholder}</p>",
            f'<pre class="mermaid">{mermaid_code}</pre>',
        )
        html_body = html_body.replace(
            placeholder,
            f'<pre class="mermaid">{mermaid_code}</pre>',
        )

    title = f"Comparison: {' vs '.join(symbols)}"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        :root {{
            --bg-dark: #1B1B1B;
            --bg-light: #F5F0EB;
            --surface: #EDE8E3;
            --accent-1: #C4533A;
            --accent-2: #2B5EA7;
            --text-dark: #1A1612;
            --text-light: #F5F0EB;
            --green: #4ecca3;
            --red: #e94560;
            --yellow: #f0a500;
        }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: 'Lato', -apple-system, BlinkMacSystemFont, sans-serif;
            background: var(--bg-dark);
            color: var(--text-light);
            line-height: 1.7;
            font-size: 16px;
            max-width: 900px;
            margin: 0 auto;
            padding: 2rem;
        }}
        h1 {{
            font-family: 'Raleway', sans-serif;
            font-size: 2.2rem;
            font-weight: 300;
            color: var(--accent-1);
            margin: 1.5rem 0;
            border-bottom: 2px solid var(--accent-1);
            padding-bottom: 0.5rem;
        }}
        h2 {{
            font-family: 'Raleway', sans-serif;
            font-size: 1.6rem;
            font-weight: 700;
            color: var(--accent-2);
            margin: 2rem 0 1rem;
        }}
        h3 {{
            font-size: 1.2rem;
            font-weight: 700;
            color: var(--text-light);
            margin: 1.5rem 0 0.5rem;
        }}
        p {{ margin: 0.8rem 0; }}
        a {{ color: var(--accent-2); text-decoration: underline; }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 1rem 0;
            font-size: 0.9rem;
        }}
        th {{
            background: var(--accent-2);
            color: white;
            padding: 0.6rem;
            text-align: left;
            font-weight: 700;
        }}
        td {{
            padding: 0.5rem 0.6rem;
            border-bottom: 1px solid #333;
        }}
        tr:nth-child(even) {{ background: rgba(255,255,255,0.03); }}
        tr:hover {{ background: rgba(255,255,255,0.07); }}
        strong {{ color: var(--accent-1); }}
        em {{ color: #aaa; font-style: italic; }}
        blockquote {{
            border-left: 3px solid var(--accent-1);
            padding: 0.5rem 1rem;
            margin: 1rem 0;
            background: rgba(255,255,255,0.03);
            font-style: italic;
        }}
        code {{
            background: rgba(255,255,255,0.08);
            padding: 0.15rem 0.4rem;
            border-radius: 3px;
            font-size: 0.85em;
        }}
        pre {{
            background: rgba(255,255,255,0.05);
            padding: 1rem;
            border-radius: 5px;
            overflow-x: auto;
            margin: 1rem 0;
        }}
        pre.mermaid {{
            background: transparent;
            text-align: center;
        }}
        hr {{
            border: none;
            border-top: 1px solid #333;
            margin: 2rem 0;
        }}
        ul, ol {{ padding-left: 1.5rem; margin: 0.5rem 0; }}
        li {{ margin: 0.3rem 0; }}
        .metadata {{
            color: #888;
            font-size: 0.9rem;
            margin-bottom: 2rem;
        }}
    </style>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;700&family=Lato:wght@300;400;700&display=swap" rel="stylesheet">
</head>
<body>
    {html_body}
    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
        mermaid.initialize({{ startOnLoad: true, theme: 'dark' }});
    </script>
</body>
</html>"""
